# Generated by Django 5.0.4 on 2024-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='milge',
            field=models.IntegerField(),
        ),
    ]
