# Generated by Django 5.0.4 on 2024-05-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_reservation_users_alter_shop_users_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='users',
            new_name='user',
        ),
    ]
