# Generated by Django 5.0.4 on 2024-05-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_rename_users_shop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brands',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuels',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='shops',
            new_name='shop',
        ),
    ]
