# Generated by Django 5.0.4 on 2024-05-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_remove_car_carcol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milge',
            new_name='milage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmition',
        ),
    ]
