# Generated by Django 5.0.4 on 2024-05-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_car_transmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fuel',
            new_name='CarModel',
        ),
        migrations.AddField(
            model_name='brand',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='booking_app.carmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid')], default='Gasoline', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=10),
        ),
        migrations.DeleteModel(
            name='car_model',
        ),
    ]
