# Generated by Django 5.0.4 on 2024-05-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_car_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='model_year',
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='booking_app.modelyear'),
            preserve_default=False,
        ),
    ]
