# Generated by Django 5.0.4 on 2024-05-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_remove_carmodel_model_year_car_model_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='booking_app.brand'),
            preserve_default=False,
        ),
    ]
