# Generated by Django 5.0.4 on 2024-05-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_remove_brand_model_carmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='booking_app.carmodel'),
            preserve_default=False,
        ),
    ]
