# Generated by Django 5.0.4 on 2024-05-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0015_remove_car_brand_car_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_app.carmodel'),
        ),
    ]
