# Generated by Django 5.0.4 on 2024-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0018_car_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='Your Description here'),
        ),
    ]
