# Generated by Django 5.0.4 on 2024-05-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0019_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking_app.shop'),
            preserve_default=False,
        ),
    ]
