# Generated by Django 5.0.4 on 2024-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0020_reservation_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
