# Generated by Django 5.0.4 on 2024-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0021_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Done', 'Done')], default='Pending', max_length=10),
        ),
    ]
