# Generated by Django 5.0.4 on 2024-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='05999999999', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
